Update to the JupyterLab 3.0 prebuilt extension system
timkpaine/jupyterlab_miami_nights pull request #14
Opened 2021-05-25 14:06 UTC by jtpio

Fixes #10 

Using the upgrade script to do most of the lifting.

![image](https://user-images.githubusercontent.com/591645/119511385-a78eb100-bd72-11eb-85f0-49194648bb6b.png)

2021-05-26 00:38 UTC, timkpaine requested changes

2021-05-26 00:38 UTC, timkpaine commented on .github/workflows/build.yml
> +        cp dist/*.tar.gz myextension.tar.gz
should this be renamed?

2021-05-26 00:38 UTC, timkpaine commented on .github/workflows/build.yml
> +        pip uninstall -y myextension jupyterlab
same

2021-05-26 00:38 UTC, timkpaine commented on .github/workflows/build.yml
> +        rm -rf myextension
same

2021-05-26 00:38 UTC, timkpaine commented on .github/workflows/build.yml
> +        name: myextension-sdist
same

2021-05-26 00:38 UTC, timkpaine commented on .github/workflows/build.yml
> +        path: myextension.tar.gz
same

2021-05-26 00:38 UTC, timkpaine commented on .github/workflows/build.yml
> +        pip install myextension.tar.gz
same

2021-05-28 21:11 UTC, merged

2021-05-29 20:18 UTC, timkpaine commented
@jtpio this is up on pypi, mind testing to make sure it works as expected?

2021-06-04 07:46 UTC, jtpio commented
Thanks @timkpaine :+1: 

Looks good when installing on Binder:

![image](https://user-images.githubusercontent.com/591645/120765694-c1ba5300-c519-11eb-8159-aff7c5b1daee.png)

2021-06-04 07:48 UTC, jtpio commented
Although some styling persists after switching back to the light theme:

![image](https://user-images.githubusercontent.com/591645/120765897-f7f7d280-c519-11eb-9763-6e65094a9289.png)

2021-06-10 17:38 UTC, jasongrout commented
> Although some styling persists after switching back to the light theme:

To fix this, likely you just need to install the `style` and `styleModule` keys in the package.json:
https://github.com/timkpaine/jupyterlab_miami_nights/blob/c5ce7911967dd3f30f25d916237381c73f6843b9/package.json#L32
https://github.com/timkpaine/jupyterlab_miami_nights/blob/c5ce7911967dd3f30f25d916237381c73f6843b9/package.json#L96

See https://github.com/telamonian/theme-darcula/pull/33 for a similar change for another theme.